# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='institute',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edge',
            name='beginDate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='edge',
            name='endDate',
            field=models.IntegerField(),
        ),
    ]
